//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class AniversarioPoupanca
{
	public virtual List<Lancamento> Lancamentos
	{
		get;
		set;
	}

	public virtual DateTime Data
	{
		get;
		set;
	}

	public virtual ContaPoupanca Poupanca
	{
		get;
		set;
	}

	public virtual ContaPoupanca ContaPoupanca
	{
		get;
		set;
	}

}

