//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class DecoratorOperacaoPacote : Operacao
{
	public virtual object Operacao
	{
		get;
		set;
	}

	public virtual Operacao OperacaoProxima
	{
		get;
		set;
	}

	public virtual void caluclaLancamento()
	{
		throw new System.NotImplementedException();
	}


    public StrategyConta Conta
    {
        get
        {
            throw new NotImplementedException();
        }
        set
        {
            throw new NotImplementedException();
        }
    }
}

