//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>Funcionario sem gerente designados são gerentes</remarks>
public class Funcionario : Pessoa
{
	public virtual string Login
	{
		get;
		set;
	}

	public virtual string Senha
	{
		get;
		set;
	}

	public virtual string Matricula
	{
		get;
		set;
	}

	public virtual Funcionario Gerente
	{
		get;
		set;
	}

}

