//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Lancamento
{
    public int Id { get; set; }

    public DateTime Momento { get; set; }

    public Decimal Valor { get; set; }

	public virtual StrategyConta Conta
	{
		get;
		set;
	}

	public virtual StrategyConta StrategyConta
	{
		get;
		set;
	}

}

