//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>As operações são realizadas na conta com referência a cobrança de pacotes ou incidência de jurou ou outras cobranças agendadas</remarks>
public interface Operacao 
{
	StrategyConta Conta { get;set; }

	void caluclaLancamento();

}

