//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class Pessoa
{
    public int Id { get; set; }

	public virtual string Nome
	{
		get;
		set;
	}

	public virtual string Email
	{
		get;
		set;
	}

	public virtual string CPF
	{
		get;
		set;
	}

}

