//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface StrategyConta 
{
    
    int Id { get; set; }

	Operacao Operacao { get;set; }

	List<Lancamento> Lancamentos { get;set; }

	Double Saldo { get;set; }

	Correntista Correntista { get;set; }

	List <Correntista> CorrentistasSecundarios { get;set; }

	string Numero { get;set; }

	Status Status { get;set; }

	void fazDeposito();

	void fazSaque();

	void listaExtrato();

}

